// Generated by Wrangler by running `wrangler types`

interface Env {
	TABBY_STORE: KVNamespace;
	NAMESPACE_ID: string; // recommended to use the same kv namespace id as wrangler.toml
	GH_CLIENT_ID: string;
	GH_CLIENT_SECRET: string;
}
